### ISSUE TITLE
Decrypting error

### ISSUE THREAD

**Issue by GrayParadox** [SteffenL/dying-light-save-editor#1]
After hellraid(beta) DLC update, the editor started to give 1 error with any new save file from that update.
Here is the error
![image](https://user-images.githubusercontent.com/68963303/89682788-00827b00-d900-11ea-888b-3b1364d3c75d.png)

**Comment by SteffenL** [comment]
Thanks for the report! I just found out that the DLC is not included in the season pass and I'm not in a rush to buy the DLC. I might be able to work on it without the DLC but I'll have to see after it has been released next week (August 13?).

**Comment by SteffenL** [comment]
I've updated the code partially for game version 1.28. Can you please give it a try?

Download:
* [Windows](https://builds.steffenl.com/download/dlse/0.1.0-dev%2bg9c29d0a/dlse-0.1.0-dev%2bg9c29d0a-win64.zip)
* [Linux](https://builds.steffenl.com/download/dlse/0.1.0-dev%2bg9c29d0a/dlse-0.1.0-dev%2bg9c29d0a-linux64.zip)

**Comment by GrayParadox** [comment]
![image](https://user-images.githubusercontent.com/68963303/89733435-1f971f00-da5e-11ea-954d-2c6adc97889d.png)

**Comment by GrayParadox** [comment]
but still 
![image](https://user-images.githubusercontent.com/68963303/89733450-363d7600-da5e-11ea-9476-788d0ecef503.png)

**Comment by SteffenL** [comment]
You can ignore the warning. Does it work all right otherwise?

**Comment by GrayParadox** [comment]
Yes, works fine.
Thank you for the fix.

**Comment by SteffenL** [comment]
Thanks. Then I'll close this issue for now and look closer at Hellraid later.
